# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-20 02:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RideRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_address', models.TextField(blank=True, null=True)),
                ('pickup_latitude', models.DecimalField(decimal_places=10, max_digits=14)),
                ('pickup_longitude', models.DecimalField(decimal_places=10, max_digits=14)),
                ('drop_off_address', models.TextField(blank=True, null=True)),
                ('drop_off_latitude', models.DecimalField(decimal_places=10, max_digits=14)),
                ('drop_off_longitude', models.DecimalField(decimal_places=10, max_digits=14)),
                ('request_time', models.DateTimeField(auto_now_add=True)),
                ('picked_up_at', models.DateTimeField(blank=True, null=True)),
                ('droped_off_at', models.DateTimeField(blank=True, null=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ride_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
